debug-mode: false
requesting:
  use-permissions: true
  allow-cross-game-mode: false
  allow-cross-world: false
  must-see: true
  max-distance: 10
  disabled-worlds: {}
  disabled-regions: {}
  timeout: 10000
  max-requests: 5
  method-allow:
    command: true
    right-click: true
    shift-right-click: false
    left-click: false
    shift-left-click: false
trading:
  options:
    allow-inventory-closing: false
    allow-dragging: true
    use-economy: true
    default-layout: default
  global-offers:
    item: {}
    experience:
      experience-item:
        material: 384
        display-name: '%experience% experience.'
      experience-item-mirror:
        material: 384
        display-name: '%player% offers %experience% experience.'
      small-modifier: 1
      large-modifier: 5
    money:
      money-item:
        material: 266
        display-name: '%money%'
      money-item-mirror:
        material: 266
        display-name: '%player% offers %money%'