requesting:
  use-permissions: false
  allow-cross-game-mode: false
  allow-cross-world: false
  must-see: true
  max-distance: 10
  disabled-worlds: {}
  disabled-regions: {}
  timeout: 10000
  max-requests: 5
  method-allow:
    command: true
    right-click: false
    shift-right-click: false
    left-click: false
    shift-left-click: false
trading:
  allow-inventory-closing: false
  use-economy: false
  offers:
    experience:
      experience-item:
        material: 384
        display-name: "%experience% experience."
        lore:
          - "Left click to add %small% level(s)"
          - "Right click to remove %small% level(s)"
          - "Shift left click to add %large% experience"
          - "Shift right click to remove %large% experience"
      experience-item-mirror:
        material: 384
        display-name: "%player% offers %experience% experience."
      small-modifier: 1
      large-modifier: 5
    money:
      money-item:
        material: 266
        display-name: "%money%"
        lore:
          - "Left click to add %small%"
          - "Right click to remove %small%"
          - "Shift left click to add %large%"
          - "Shift right click to remove %large%"
      money-item-mirror:
        material: 266
        display-name: "%money%"
      small-modifier: 1
      large-modifier: 5
    item: {}
