requesting:
  use-permissions: false
  allow-cross-game-mode: false
  allow-cross-world: false
  must-see: true
  max-distance: 10
  disabled-worlds: {}
  disabled-regions: {}
  timeout: 10000
  max-requests: 5
  method-allow:
    command: true
    right-click: true
    shift-right-click: true
    left-click: false
    shift-left-click: false
trading:
  allow-inventory-closing: true
offers:
  experience:
    item:
      material: 384
      display-name: "You added %levels% levels."
      lore:
        - "Left click to add %small% level(s)"
        - "Right click to remove %small% level(s)"
        - "Shift left click to add %large% levels"
        - "Shift right click to remove %large% levels"
    item-mirror:
      material: 384
      display-name: "%player% offers %levels% levels."
    small-modifier: 1
    large-modifier: 5
  item: {}
