package me.josvth.trade.transaction.offer.click;

public enum OfferClickType {

    OFFER_LEFT,
    OFFER_SHIFT_LEFT,
    OFFER_RIGHT,
    OFFER_SHIFT_RIGHT,
    OFFER_WINDOW_BORDER_LEFT,
    OFFER_WINDOW_BORDER_RIGHT,
    OFFER_MIDDLE,
    OFFER_NUMBER_KEY,
    OFFER_DOUBLE_CLICK,
    OFFER_DROP,
    OFFER_CONTROL_DROP,
    OFFER_CREATIVE,
    OFFER_UNKNOWN,
    CURSOR_LEFT,
    CURSOR_SHIFT_LEFT,
    CURSOR_RIGHT,
    CURSOR_SHIFT_RIGHT,
    CURSOR_WINDOW_BORDER_LEFT,
    CURSOR_WINDOW_BORDER_RIGHT,
    CURSOR_MIDDLE,
    CURSOR_NUMBER_KEY,
    CURSOR_DOUBLE_CLICK,
    CURSOR_DROP,
    CURSOR_CONTROL_DROP,
    CURSOR_CREATIVE,
    CURSOR_UNKNOWN;


}
